# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_RWrapperMiscellaneousPkg_wrappers", use_symbols = TRUE, package_name = "RWrapperMiscellaneousPkg")

#' @docType package
#' @usage NULL
#' @useDynLib RWrapperMiscellaneousPkg, .registration = TRUE
NULL

#' This function returns the transpose matrix
#' @export
transpose_matrix <- function(mat_one) .Call(wrap__transpose_matrix, mat_one)

#' This function returns the min value of a function
#' @export
min_matrix <- function(mat_one) .Call(wrap__min_matrix, mat_one)

#' This function returns the max value of a function
#' @export
max_matrix <- function(mat_one) .Call(wrap__max_matrix, mat_one)

#' This function calcluates the abs of a matrix
#' @export
abs_matrix <- function(mat_one) .Call(wrap__abs_matrix, mat_one)

#' This function calcluates the dot product of two function
#' @export
dot_product_matrix <- function(mat_one, mat_two) .Call(wrap__dot_product_matrix, mat_one, mat_two)

#' This function subtract two matrices
#' @export
sub_matrix <- function(mat_one, mat_two) .Call(wrap__sub_matrix, mat_one, mat_two)

#' This function add to matrices
#' @export
add_matrix <- function(mat_one, mat_two) .Call(wrap__add_matrix, mat_one, mat_two)

#' This function multiplies to matrices
#' @export
mul_matrix <- function(mat_one, mat_two) .Call(wrap__mul_matrix, mat_one, mat_two)

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

#' Read a text file out and return a string
#' @export
#' @examples
#' read_file_to_string("test_file1.txt")
read_file_to_string <- function(file_path) .Call(wrap__read_file_to_string, file_path)

write_file_from_char_vec <- function(file_path, input_vec, append) .Call(wrap__write_file_from_char_vec, file_path, input_vec, append)

#' Get hamming Distance of two strings
#' @export
#' @examples hamming('hallo welt','hallo test')
hamming <- function(alpha_str, beta_str) .Call(wrap__hamming, alpha_str, beta_str)

#' Get levenshtein distance of two strings
#' @export
#' @examples levenshtein('hallo welt', 'hallo test')
levenshtein <- function(alpha_str, beta_str) .Call(wrap__levenshtein, alpha_str, beta_str)

#' levenshtein_smid matching of two strings
#' @export
#' @examples levenshtein_smid('hallo welt', 'hallo test')
levenshtein_smid <- function(alpha_str, beta_str) .Call(wrap__levenshtein_smid, alpha_str, beta_str)

#' hamming_smid matching of two strings
#' @export
#' @examples hamming_smid('hallo welt', 'hallo test')
hamming_smid <- function(alpha_str, beta_str) .Call(wrap__hamming_smid, alpha_str, beta_str)

#' bom matching of two strings
#' @export
#' @examples bom_matching('hallo welt', 'hallo test')
bom_matching <- function(pattern, text) .Call(wrap__bom_matching, pattern, text)

#' bndm matching of two strings
#' @export
#' @examples bndm_matching('hallo welt', 'hallo test')
bndm_matching <- function(pattern, text) .Call(wrap__bndm_matching, pattern, text)

#' horspool matching of two strings
#' @export
#' @examples horspool_matching('hallo welt', 'hallo test')
horspool_matching <- function(pattern, text) .Call(wrap__horspool_matching, pattern, text)

#' kmp matching of two strings
#' @export
#' @examples kmp_matching('hallo welt', 'hallo test')
kmp_matching <- function(pattern, text) .Call(wrap__kmp_matching, pattern, text)

#' Return sha224 hash of a string to R.
#' @export
#' @examples get_sha224("Hallo Welt")
get_sha224 <- function(input) .Call(wrap__get_sha224, input)

#' Return sha256 hash of a string to R.
#' @export
#' @examples get_sha256("Hallo Welt")
get_sha256 <- function(input) .Call(wrap__get_sha256, input)

#' Return sha384 hash of a string to R.
#' @export
#' @examples get_sha384("Hallo Welt")
get_sha384 <- function(input) .Call(wrap__get_sha384, input)

#' Return sha512 hash of an input string to R.
#' @export
#' @examples get_sha512("Hallo Welt")
get_sha512 <- function(input) .Call(wrap__get_sha512, input)

#' Return sha1 hash of an input string to R.
#' @export
#' @examples
#' get_sha1("Hallo Welt")
get_sha1 <- function(input) .Call(wrap__get_sha1, input)

#' get random number in a range
#' @export
#' @examples
#' get_random_number_range(0,1000)
get_random_number_range <- function(min_num, max_num) .Call(wrap__get_random_number_range, min_num, max_num)

#' return a fake city name
#' @export
#' @examples
#' get_city()
get_city <- function() .Call(wrap__get_city)

#' return a fake country
#' @export
#' @examples
#' get_country()
get_country <- function() .Call(wrap__get_country)

#' return a fake country abr
#' @export
#' @examples
#' get_country_abr()
get_country_abr <- function() .Call(wrap__get_country_abr)

#' return a fake latitude
#' @export
#' @examples
#' get_latitude()
get_latitude <- function() .Call(wrap__get_latitude)

#' return a fake longitude
#' @export
#' @examples
#' get_longitude()
get_longitude <- function() .Call(wrap__get_longitude)

#' return a fake state
#' @export
#' @examples
#' get_state()
get_state <- function() .Call(wrap__get_state)

#' return a fake state
#' @export
#' @examples
#' get_street_name()
get_street_name <- function() .Call(wrap__get_street_name)

#' return a fake state number
#' @export
#' @examples
#' get_street_number()
get_street_number <- function() .Call(wrap__get_street_number)

#' return a fake state prefix
#' @export
#' @examples
#' get_street_prefix()
get_street_prefix <- function() .Call(wrap__get_street_prefix)

#' return fake street suffix
#' @export
#' @examples
#' get_street_suffix()
get_street_suffix <- function() .Call(wrap__get_street_suffix)

#' return fake street suffix
#' @export
#' @examples
#' get_zip()
get_zip <- function() .Call(wrap__get_zip)

#' return fake animal
#' @export
#' @examples
#' get_anmimal()
get_anmimal <- function() .Call(wrap__get_anmimal)

#' return fake cat
#' @export
#' @examples
#' get_cat()
get_cat <- function() .Call(wrap__get_cat)

#' return fake dog
#' @export
#' @examples
#' get_dog()
get_dog <- function() .Call(wrap__get_dog)

#' return fake farm animal
#' @export
#' @examples
#' get_farm()
get_farm <- function() .Call(wrap__get_farm)

#' return fake pet name
#' @export
#' @examples
#' get_pet_name()
get_pet_name <- function() .Call(wrap__get_pet_name)

#' return fake pet name
#' @export
#' @examples
#' get_alcohol()
get_alcohol <- function() .Call(wrap__get_alcohol)

#' return fake blg
#' @export
#' @examples
#' get_blg()
get_blg <- function() .Call(wrap__get_blg)

#' return fake hop
#' @export
#' @examples
#' get_hop()
get_hop <- function() .Call(wrap__get_hop)

#' return fake ibu
#' @export
#' @examples
#' get_ibu()
get_ibu <- function() .Call(wrap__get_ibu)

#' return fake malt
#' @export
#' @examples
#' get_malt()
get_malt <- function() .Call(wrap__get_malt)

#' return fake beer name
#' @export
#' @examples
#' get_name()
get_name <- function() .Call(wrap__get_name)

#' return fake beer style
#' @export
#' @examples
#' get_style()
get_style <- function() .Call(wrap__get_style)

#' return fake beer yeast
#' @export
#' @examples
#' get_yeast()
get_yeast <- function() .Call(wrap__get_yeast)

#' return fake bool
#' @export
#' @examples
#' get_bool()
get_bool <- function() .Call(wrap__get_bool)

#' return full color
#' @export
#' @examples
#' get_full_color()
get_full_color <- function() .Call(wrap__get_full_color)

#' return hex color
#' @export
#' @examples
#' get_hex_color()
get_hex_color <- function() .Call(wrap__get_hex_color)

#' return safe color
#' @export
#' @examples
#' get_safe_color()
get_safe_color <- function() .Call(wrap__get_safe_color)

#' return fake company
#' @export
#' @examples
#' get_company()
get_company <- function() .Call(wrap__get_company)

#' return buzz word
#' @export
#' @examples
#' get_buzzword()
get_buzzword <- function() .Call(wrap__get_buzzword)

#' return bs
#' @export
#' @examples
#' get_bs()
get_bs <- function() .Call(wrap__get_bs)

#' return company suffix
#' @export
#' @examples
#' get_company_suffix()
get_company_suffix <- function() .Call(wrap__get_company_suffix)

#' return fake email
#' @export
#' @examples
#' get_email()
get_email <- function() .Call(wrap__get_email)

#' return fake phone number
#' @export
#' @examples
#' get_phone()
get_phone <- function() .Call(wrap__get_phone)

#' return formatted phone number
#' @export
#' @examples
#' get_phone_formatted()
get_phone_formatted <- function() .Call(wrap__get_phone_formatted)

#' return currency long
#' @export
#' @examples
#' get_currency_long()
get_currency_long <- function() .Call(wrap__get_currency_long)

#' return currency short
#' @export
#' @examples
#' get_currency_short()
get_currency_short <- function() .Call(wrap__get_currency_short)

#' return day
#' @export
#' @examples
#' get_day()
get_day <- function() .Call(wrap__get_day)

#' return hour
#' @export
#' @examples
#' get_hour()
get_hour <- function() .Call(wrap__get_hour)

#' return minute
#' @export
#' @examples
#' get_minute()
get_minute <- function() .Call(wrap__get_minute)

#' return secound
#' @export
#' @examples
#' get_secound()
get_secound <- function() .Call(wrap__get_secound)

#' return secound
#' @export
#' @examples
#' get_timezone()
get_timezone <- function() .Call(wrap__get_timezone)

#' return week day
#' @export
#' @examples
#' get_week_day()
get_week_day <- function() .Call(wrap__get_week_day)

#' return year
#' @export
#' @examples
#' get_year()
get_year <- function() .Call(wrap__get_year)

#' return file extension
#' @export
#' @examples
#' get_extension()
get_extension <- function() .Call(wrap__get_extension)

#' return mime type
#' @export
#' @examples
#' get_mime_type()
get_mime_type <- function() .Call(wrap__get_mime_type)

#' return abbreviation
#' @export
#' @examples
#' get_abbreviation()
get_abbreviation <- function() .Call(wrap__get_abbreviation)

#' return adjective
#' @export
#' @examples
#' get_adjective()
get_adjective <- function() .Call(wrap__get_adjective)

#' return ingverb
#' @export
#' @examples
#' get_ingverb()
get_ingverb <- function() .Call(wrap__get_ingverb)

#' add two numbers
#' @export
#' @examples add_num(5, 3)
add_num <- function(a, b) .Call(wrap__add_num, a, b)

#' sub two numbers
#' @export
#' @examples sub_num(5, 3)
sub_num <- function(a, b) .Call(wrap__sub_num, a, b)

#' multiply two numbers
#' @export
#' @examples mul_num(5, 3)
mul_num <- function(a, b) .Call(wrap__mul_num, a, b)

#' div two numbers
#' @export
#' @examples div_num(5, 3)
div_num <- function(a, b) .Call(wrap__div_num, a, b)

#' calculate the modulo of two numbers
#' @export
#' @examples mod_num(5, 3)
mod_num <- function(a, b) .Call(wrap__mod_num, a, b)

#' return a fake state
#' @export
#' @examples
#' get_street()
get_street <- function() .Call(wrap__get_street)

#' return a fake noun word
#' @export
#' @examples get_noun()
get_noun <- function() .Call(wrap__get_noun)

#' return a fake pharse word
#' @export
#' @examples get_pharse()
get_pharse <- function() .Call(wrap__get_pharse)

#' return a fake verb
#' @export
#' @examples get_verb()
get_verb <- function() .Call(wrap__get_verb)

#' return a hippster word
#' @export
#' @examples get_hippster_word()
get_hippster_word <- function() .Call(wrap__get_hippster_word)

#' return a domain name
#' @export
#' @examples get_domain_name()
get_domain_name <- function() .Call(wrap__get_domain_name)

#' return a domain suffix
#' @export
#' @examples get_domain_suffix()
get_domain_suffix <- function() .Call(wrap__get_domain_suffix)

#' return a http method
#' @export
#' @examples get_http_method()
get_http_method <- function() .Call(wrap__get_http_method)

#' return a ipv4 address
#' @export
#' @examples get_ipv4_address()
get_ipv4_address <- function() .Call(wrap__get_ipv4_address)

#' return a ipv6 ddress
#' @export
#' @examples get_ipv6_address()
get_ipv6_address <- function() .Call(wrap__get_ipv6_address)

#' return a mac ddress
#' @export
#' @examples get_mac_address()
get_mac_address <- function() .Call(wrap__get_mac_address)

#' return a username
#' @export
#' @examples get_username()
get_username <- function() .Call(wrap__get_username)

#' return a job descriptor
#' @export
#' @examples get_job_descriptor()
get_job_descriptor <- function() .Call(wrap__get_job_descriptor)

#' return a job level
#' @export
#' @examples get_job_level()
get_job_level <- function() .Call(wrap__get_job_level)

#' return a job title
#' @export
#' @examples get_job_title()
get_job_title <- function() .Call(wrap__get_job_title)

#' return a language abbreviation
#' @export
#' @examples get_language_abbreviation()
get_language_abbreviation <- function() .Call(wrap__get_language_abbreviation)

#' return a language programming
#' @export
#' @examples get_language_programming()
get_language_programming <- function() .Call(wrap__get_language_programming)

#' return a language programming
#' @export
#' @examples get_language_random()
get_language_random <- function() .Call(wrap__get_language_random)

#' return a log level appache
#' @export
#' @examples get_log_level_appache()
get_log_level_appache <- function() .Call(wrap__get_log_level_appache)

#' return a log level general
#' @export
#' @examples get_log_level_general()
get_log_level_general <- function() .Call(wrap__get_log_level_general)

#' return a log sys log
#' @export
#' @examples get_log_level_sys_log()
get_log_level_sys_log <- function() .Call(wrap__get_log_level_sys_log)

#' return a full name
#' @export
#' @examples get_full_name()
get_full_name <- function() .Call(wrap__get_full_name)

#' return a first name
#' @export
#' @examples get_first_name()
get_first_name <- function() .Call(wrap__get_first_name)

#' return a last name
#' @export
#' @examples get_last_name()
get_last_name <- function() .Call(wrap__get_last_name)

#' return a prefix name
#' @export
#' @examples get_prefix_name()
get_prefix_name <- function() .Call(wrap__get_prefix_name)

#' return a suffix name
#' @export
#' @examples get_suffix_name()
get_suffix_name <- function() .Call(wrap__get_suffix_name)

#' return a fake password
#' @export
#' @examples get_generate_password(TRUE,TRUE,TRUE,8)
get_generate_password <- function(upper, numeric, special, num) .Call(wrap__get_generate_password, upper, numeric, special, num)

#' return a credit card type
#' @export
#' @examples get_credit_card_type()
get_credit_card_type <- function() .Call(wrap__get_credit_card_type)

#' return a credit card number
#' @export
#' @examples get_credit_card_number()
get_credit_card_number <- function() .Call(wrap__get_credit_card_number)

#' return a credit card luhn number
#' @export
#' @examples get_credit_card_luhn_number()
get_credit_card_luhn_number <- function() .Call(wrap__get_credit_card_luhn_number)

#' return a credit card luhn number
#' @export
#' @examples get_credit_card_exp()
get_credit_card_exp <- function() .Call(wrap__get_credit_card_exp)

#' return a credit card luhn number
#' @export
#' @examples get_credit_card_ccv()
get_credit_card_ccv <- function() .Call(wrap__get_credit_card_ccv)

#' return a status code
#' @export
#' @examples get_status_codes_general()
get_status_codes_general <- function() .Call(wrap__get_status_codes_general)

#' return a status code simple
#' @export
#' @examples get_status_codes_simple()
get_status_codes_simple <- function() .Call(wrap__get_status_codes_simple)

#' return a uuid v1
#' @export
#' @examples get_uuid_v1()
get_uuid_v1 <- function() .Call(wrap__get_uuid_v1)

#' return a uuid v4
#' @export
#' @examples get_uuid_v4()
get_uuid_v4 <- function() .Call(wrap__get_uuid_v4)

#' return a user agent chrome
#' @export
#' @examples get_user_agent_chrome()
get_user_agent_chrome <- function() .Call(wrap__get_user_agent_chrome)

#' return a user agent firefox
#' @export
#' @examples get_user_agent_firefox()
get_user_agent_firefox <- function() .Call(wrap__get_user_agent_firefox)

#' return a user agent platform token
#' @export
#' @examples get_user_agent_linux_platform_token()
get_user_agent_linux_platform_token <- function() .Call(wrap__get_user_agent_linux_platform_token)

#' return a user agent mac platform token
#' @export
#' @examples get_user_agent_mac_platform_token()
get_user_agent_mac_platform_token <- function() .Call(wrap__get_user_agent_mac_platform_token)

#' return a get user agent opera
#' @export
#' @examples get_user_agent_opera()
get_user_agent_opera <- function() .Call(wrap__get_user_agent_opera)

#' return a get user random platform
#' @export
#' @examples get_user_agent_random_platform()
get_user_agent_random_platform <- function() .Call(wrap__get_user_agent_random_platform)

#' return a get user agent safari
#' @export
#' @examples get_user_agent_safari()
get_user_agent_safari <- function() .Call(wrap__get_user_agent_safari)

#' return a get user windows platform
#' @export
#' @examples get_user_agent_windows_platform_token()
get_user_agent_windows_platform_token <- function() .Call(wrap__get_user_agent_windows_platform_token)

#' return a car maker
#' @export
#' @examples get_car_maker()
get_car_maker <- function() .Call(wrap__get_car_maker)

#' return a car model
#' @export
#' @examples get_car_model()
get_car_model <- function() .Call(wrap__get_car_model)

#' return a car fuel
#' @export
#' @examples get_fuel()
get_fuel <- function() .Call(wrap__get_fuel)

#' return a transmission gear
#' @export
#' @examples get_transmission_gear()
get_transmission_gear <- function() .Call(wrap__get_transmission_gear)

#' return a vehicle type
#' @export
#' @examples get_vehicle_type()
get_vehicle_type <- function() .Call(wrap__get_vehicle_type)

#' return a paragraph
#' @export
#' @examples get_paragraph(10,20,10,",")
get_paragraph <- function(count, sentence_count, word_count, separator) .Call(wrap__get_paragraph, count, sentence_count, word_count, separator)

#' return a question
#' @export
#' @examples get_question()
get_question <- function() .Call(wrap__get_question)

#' return a quote
#' @export
#' @examples get_quote()
get_quote <- function() .Call(wrap__get_quote)

#' return a quote
#' @export
#' @examples get_sentence(10)
get_sentence <- function(word_count) .Call(wrap__get_sentence, word_count)

#' return a quote
#' @export
#' @examples get_word()
get_word <- function() .Call(wrap__get_word)

#' return a HTTP Response
#' @examples send_custom_http_request('https://httpbin.org/get','GET',list(),list(),list(),"")
#' send_custom_http_request('https://httpbin.org/post','POST',list(),list(),list(),"")
send_custom_http_request <- function(url, method, request_headers, request_query_params, request_form, request_body) .Call(wrap__send_custom_http_request, url, method, request_headers, request_query_params, request_form, request_body)

#' Resize an image
#' @export
#' @description The filter option should be Nearest, Triangle, CatmullRom, Gaussian, Lanczos3
#' The default option for the image Lanczos3
#' @export
#' @examples resize_image('20220824_214140.jpg',500,500,'Nearest','20220824_214140_nearest.jpg',TRUE)
#' resize_image('20220824_214212.jpg',500,500,'Triangle','20220824_214212_triangle.jpg',TRUE)
#' resize_image('20220824_214215.jpg',500,500,'CatmullRom','20220824_214215_catmullRom.jpg',TRUE)
#' resize_image('20220824_214219.jpg',500,500,'Gaussian','20220824_214219_gaussian.jpg',TRUE)
#' resize_image('20220824_214217.jpg',500,500,'Lanczos3','20220824_214217_lanczos3.jpg',TRUE)
resize_image <- function(path, nwidth, nheight, filter, path_new_image, only_shrink) .Call(wrap__resize_image, path, nwidth, nheight, filter, path_new_image, only_shrink)

#' write json to excel
#' @description This is a function to write json arrays or json objects to an excel sheet
#' @export
#' @examples
#' write_sheet_by_name('example.xlsx',"Test1",jsonlite::toJSON(mtcars))
write_sheet_by_name <- function(file_path, sheet_name, json_input_str) .Call(wrap__write_sheet_by_name, file_path, sheet_name, json_input_str)

#' read excel sheet by name to json
#' @description This is a function to read out the content out of a excel sheet to json array
#' @export
#' @examples
#' read_sheet_by_name("example_input.xlsx","Test1")
read_sheet_by_name <- function(file_path, sheet_name) .Call(wrap__read_sheet_by_name, file_path, sheet_name)

#' convert an xml string to json
#' @description This function converts an xml string to json
#' @export
#' @examples
#' inputStr <- "<dataset>
#'                    <record>
#'                        <id>1</id>
#'                         <first_name>Nerita</first_name>
#'                          <last_name>Stanney</last_name>
#'                          <email>nstanney0@domainmarket.com</email>
#'                          <gender>Female</gender>
#'                          <ip_address>223.10.217.33</ip_address>
#'                     </record>
#'        </dataset>"
#' xml_to_json(inputStr)
#' 
xml_to_json <- function(xml_input_str) .Call(wrap__xml_to_json, xml_input_str)

#' This function checks if an input string matches with an regex input
#' @export
#' @examples
#' match_regex_string("^[0-9]*$","153020")
match_regex_string <- function(regex_input, seach_string) .Call(wrap__match_regex_string, regex_input, seach_string)

#' This function replaces a regex in an input string
#' @export
#' @examples
#' replace_regex_string("1020 Wien","[^0-9]+","")
replace_regex_string <- function(input_string, regex_input, replace_str) .Call(wrap__replace_regex_string, input_string, regex_input, replace_str)

#' This function split an input string to parts
#' @export
#' @examples
#' split_regex_string("a b c d e","[ ]+")
split_regex_string <- function(input_string, regex_input) .Call(wrap__split_regex_string, input_string, regex_input)

#' Get Data from diffrent databases
#' @export
#' @examples
#' \dontrun{
#' query_db("postgresql://postgres:postgres@localhost:5500/test1db","SELECT false::bool as false_val",list(),5)
#' }
query_db <- function(config, query, parameter, max_connection) .Call(wrap__query_db, config, query, parameter, max_connection)

#' This is a wrapper for [cs_shake_v256](https://docs.rs/tiny-keccak/latest/tiny_keccak/struct.CShake.html)
#' @export
#' @examples
#' cs_shake_v256(as.raw(""),as.raw(""),as.raw("Hallo Welt"))
cs_shake_v256 <- function(name, custom_string, input) .Call(wrap__cs_shake_v256, name, custom_string, input)

#' This is a wrapper for [kangaroo_twelve_xof](https://docs.rs/tiny-keccak/latest/tiny_keccak/struct.KangarooTwelveXof.html)
#' @export
#' @examples
#' kangaroo_twelve_xof(as.raw("Hallo Welt"),as.raw("Test"))
kangaroo_twelve_xof <- function(custom_string, input) .Call(wrap__kangaroo_twelve_xof, custom_string, input)

#' This is a wrapper for [kangaroo_twelve](https://docs.rs/tiny-keccak/latest/tiny_keccak/struct.KangarooTwelve.html)
#' @export
#' @examples
#' kangaroo_twelve_xof(as.raw("Hallo Welt"),as.raw("Test"))
kangaroo_twelve <- function(custom_string, input) .Call(wrap__kangaroo_twelve, custom_string, input)

#' This is a wrapper for [cs_shake_v128](https://docs.rs/tiny-keccak/latest/tiny_keccak/struct.CShake.html)
#' @export
#' @examples
#' cs_shake_v128(as.raw("Hallo Welt"),as.raw("Test"),as.raw("Rust"))
cs_shake_v128 <- function(name, custom_string, input) .Call(wrap__cs_shake_v128, name, custom_string, input)

#' This is a wrapper for [keccak_v224](https://docs.rs/tiny-keccak/latest/tiny_keccak/struct.Keccak.html)
#' @export
#' @examples
#' keccak_v224(as.raw("Rust"))
keccak_v224 <- function(input) .Call(wrap__keccak_v224, input)

#' This is a wrapper for [keccak_v256](https://docs.rs/tiny-keccak/latest/tiny_keccak/struct.Keccak.html)
#' @export
#' @examples
#' keccak_v256(as.raw("Rust")) 
keccak_v256 <- function(input) .Call(wrap__keccak_v256, input)

#' This is a wrapper for [keccak_v384](https://docs.rs/tiny-keccak/latest/tiny_keccak/struct.Keccak.html)
#' @export
#' @examples
#' keccak_v384(as.raw("Rust")) 
keccak_v384 <- function(input) .Call(wrap__keccak_v384, input)

#' This is a wrapper for [keccak_v512](https://docs.rs/tiny-keccak/latest/tiny_keccak/struct.CShake.html)
#' @export
#' @examples
#' keccak_v512(as.raw("Rust")) 
keccak_v512 <- function(input) .Call(wrap__keccak_v512, input)

#' This is a wrapper for [kmac_v128](https://docs.rs/tiny-keccak/latest/tiny_keccak/struct.Kmac.html)
#' @export
#' @examples
#' kmac_v128(as.raw("Hallo Welt"),as.raw("Test"),as.raw("Rust")) 
kmac_v128 <- function(key, custom_string, input) .Call(wrap__kmac_v128, key, custom_string, input)

#' This is a wrapper for [kmac_v256](https://docs.rs/tiny-keccak/latest/tiny_keccak/struct.Kmac.html)
#' @export
#' @examples
#' kmac_v256(as.raw("Hallo Welt"),as.raw("Test"),as.raw("Rust")) 
kmac_v256 <- function(key, custom_string, input) .Call(wrap__kmac_v256, key, custom_string, input)

#' This is a wrapper for [kmac_v256_xof](https://docs.rs/tiny-keccak/latest/tiny_keccak/struct.KmacXof.html)
#' @export
#' @examples
#' kmac_v256_xof(as.raw("Hallo Welt"),as.raw("Test"),as.raw("Rust")) 
kmac_v256_xof <- function(key, input, custom_string) .Call(wrap__kmac_v256_xof, key, input, custom_string)

#' This is a wrapper for [kmac_v128_xof](/// This is a wrapper for [kmac_v128_xof](https://docs.rs/tiny-keccak/latest/tiny_keccak/struct.CShake.html)
#' @export
#' @examples
#' kmac_v128_xof(as.raw("Hallo Welt"),as.raw("Test"),as.raw("Rust")) 
kmac_v128_xof <- function(key, input, custom_string) .Call(wrap__kmac_v128_xof, key, input, custom_string)

#' This is a wrapper for [parallel_hash_v128](https://docs.rs/tiny-keccak/latest/tiny_keccak/struct.ParallelHash.html)
#' @export
#' @examples
#' parallel_hash_v128(as.raw("Hallo Welt"),as.raw("Test"),32)  
parallel_hash_v128 <- function(custom_string, input, block_size) .Call(wrap__parallel_hash_v128, custom_string, input, block_size)

#' This is a wrapper for [parallel_hash_v256](https://docs.rs/tiny-keccak/latest/tiny_keccak/struct.ParallelHash.html)
#' @export
#' @examples
#' parallel_hash_v256(as.raw("Hallo Welt"),as.raw("Test"),32)  
parallel_hash_v256 <- function(custom_string, input, block_size) .Call(wrap__parallel_hash_v256, custom_string, input, block_size)

#' This is a wrapper for [sha3_v224](https://docs.rs/tiny-keccak/latest/tiny_keccak/struct.Sha3.html)
#' @export
#' @examples
#' sha3_v224(as.raw("Hallo Welt"))  
sha3_v224 <- function(input) .Call(wrap__sha3_v224, input)

#' This is a wrapper for [sha3_v384](https://docs.rs/tiny-keccak/latest/tiny_keccak/struct.Sha3.html)
#' @export
#' @examples
#' sha3_v384(as.raw("Hallo Welt")) 
sha3_v384 <- function(input) .Call(wrap__sha3_v384, input)

#' This is a wrapper for [sha3_v512](https://docs.rs/tiny-keccak/latest/tiny_keccak/struct.Sha3.html)
#' @export
#' @examples
#' sha3_v512(as.raw("Hallo Welt"))
sha3_v512 <- function(input) .Call(wrap__sha3_v512, input)

#' This is a wrapper for [shake_v128](https://docs.rs/tiny-keccak/latest/tiny_keccak/struct.Shake.html)
#' @export
#' @examples
#' shake_v128(as.raw("Hallo Welt"))
shake_v128 <- function(input) .Call(wrap__shake_v128, input)

#' This is a wrapper for [shake_v256](https://docs.rs/tiny-keccak/latest/tiny_keccak/struct.Shake.html)
#' @export
#' @examples
#' shake_v256(as.raw("Hallo Welt"))
shake_v256 <- function(input) .Call(wrap__shake_v256, input)

#' This is a wrapper for [tuple_hash_v128](https://docs.rs/tiny-keccak/latest/tiny_keccak/struct.TupleHash.html)
#' @export
#' @examples
#' tuple_hash_v128(as.raw("Hallo Welt"),as.raw("Rust"))
tuple_hash_v128 <- function(custom_string, input) .Call(wrap__tuple_hash_v128, custom_string, input)

#' This is a wrapper for [tuple_hash_v128_xof](https://docs.rs/tiny-keccak/latest/tiny_keccak/struct.TupleHashXof.html)
#' @export
#' @examples
#' tuple_hash_v128_xof(as.raw("Hallo Welt"),as.raw("Rust"))
tuple_hash_v128_xof <- function(custom_string, input) .Call(wrap__tuple_hash_v128_xof, custom_string, input)

#' This is a wrapper for [tuple_hash_v256](https://docs.rs/tiny-keccak/latest/tiny_keccak/struct.TupleHash.html)
#' @export
#' @examples
#' tuple_hash_v256(as.raw("Hallo Welt"),as.raw("Rust"))
tuple_hash_v256 <- function(custom_string, input) .Call(wrap__tuple_hash_v256, custom_string, input)

#' This function converts an json str to to an RList
#' @export
json_str_to_robj <- function(input_str) .Call(wrap__json_str_to_robj, input_str)

#' convert an xml string to json
#' @description This function converts an xml string to an robj
#' @export
#' @examples
#' inputStr <- "<dataset>
#'                    <record>
#'                        <id>1</id>
#'                         <first_name>Nerita</first_name>
#'                          <last_name>Stanney</last_name>
#'                          <email>nstanney0@domainmarket.com</email>
#'                          <gender>Female</gender>
#'                          <ip_address>223.10.217.33</ip_address>
#'                     </record>
#'        </dataset>"
#' xml_to_robj(inputStr)
#' 
xml_to_robj <- function(xml_input_str) .Call(wrap__xml_to_robj, xml_input_str)

